name: check-changed-files
on: [pull_request]
jobs:
  test-mergability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/helloworld
      - run: echo "hello"
      - run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          RET=$(curl -s -X GET -G $URL | jq -r '.[] | .sha')
          echo $RET
          NUM=`echo $RET | wc -w`
          if [ $((NUM % 2)) -eq 1 ]; then
            echo "ok"
          else
            echo "puding"
            exit 1
          fi
