name: check-changed-files
on: [pull_request]
jobs:
  test-clone:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          RET=$(curl -s -X GET -G $URL | jq -r '.[] | .sha')
          NUM=`echo $RET | wc -l`
          if [ $NUM -eq 1 ]; then
            echo "ok"
          else
            echo "puding"
          fi
